api-version: 1.21.5
name: ChallengePlugin
version: 1.0
main: challenge.plugin.ChallengeServerPlugin
softdepend: [Multiverse-Core]
commands:
  lobby:
    description: Teleport to lobby
    usage: /lobby
